openapi: 3.0.0
info:
  title: Mojodex API Background
  version: 1.0.0
paths:
  /events_generation:
    post:
      summary: Generate various types of events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - datetime
                - event_type
                - data
              properties:
                datetime:
                  type: string
                  format: date-time
                event_type:
                  type: string
                  enum:
                    - action_driven_notifications
                    - daily_notifications
                    - daily_emails
                    - todo_daily_emails
                    - calendar_suggestion_notifications
                data:
                  type: object
      responses:
        '200':
          description: Event generation process started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        '400':
          description: Invalid inputs provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Error generating events
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /extract_todos:
    post:
      summary: Start the process to extract todos from a user task execution
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - datetime
                - user_task_execution_pk
              properties:
                datetime:
                  type: string
                  format: date-time
                user_task_execution_pk:
                  type: integer
      responses:
        '200':
          description: Process to extract todos started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        '400':
          description: Invalid inputs provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Error in extract todos route or user_task_execution not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /first_session_message:
    post:
      summary: Start a process to generate a session title based on the first message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - session_id
                - datetime
                - sender
                - message
              properties:
                session_id:
                  type: string
                datetime:
                  type: string
                  format: date-time
                sender:
                  type: string
                message:
                  type: string
      responses:
        '200':
          description: Process to generate session title started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        '400':
          description: Invalid input provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Session not found or error in first session message
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /parse_website:
    post:
      summary: Parse a website and create a document
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - datetime
                - company_pk
                - website_url
                - user_id
              properties:
                datetime:
                  type: string
                  format: date-time
                company_pk:
                  type: integer
                website_url:
                  type: string
                  format: uri
                user_id:
                  type: string
      responses:
        '200':
          description: Website parsing initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        '400':
          description: Invalid input provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Error occurred during website parsing or company not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /reschedule_todo:
    post:
      summary: Reschedule a todo item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - datetime
                - todo_pk
              properties:
                datetime:
                  type: string
                  format: date-time
                todo_pk:
                  type: integer
      responses:
        '200':
          description: Process to reschedule todo started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        '400':
          description: Invalid inputs provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Todo not found or error in reschedule todos route
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /task_tool_execution:
    post:
      summary: Execute a task tool based on the provided primary key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - datetime
                - task_tool_execution_pk
              properties:
                datetime:
                  type: string
                  format: date-time
                task_tool_execution_pk:
                  type: integer
      responses:
        '200':
          description: Process started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        '400':
          description: Invalid inputs provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Task tool execution not found or error in task tool execution
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /update_document:
    post:
      summary: Update a document
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - datetime
                - document_pk
                - edition
                - user_id
              properties:
                datetime:
                  type: string
                  format: date-time
                document_pk:
                  type: integer
                edition:
                  type: string
                user_id:
                  type: string
      responses:
        '200':
          description: Document updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        '400':
          description: Invalid input provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Document not found for this user or error updating document
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /user_task_execution_title_and_summary:
    post:
      summary: Start the process for managing user task execution title and summary
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - datetime
                - user_task_execution_pk
              properties:
                datetime:
                  type: string
                  format: date-time
                user_task_execution_pk:
                  type: integer
      responses:
        '200':
          description: Process started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
        '400':
          description: Invalid inputs provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Error in managing user task execution title and summary or user_task_execution not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string