export const socketEvents = {
  CONNECT: "connect",
  START_SESSION: "start_session",
  MOJO_TOKEN: "mojo_token",
  MOJO_MESSAGE: "mojo_message",
  DISCONNECT: "disconnect",
  ERROR: "error",
  CONNECT_ERROR: "connect_error",
  CONNECT_TIMEOUT: "connect_timeout",
  DRAFT_TOKEN: "draft_token",
  DRAFT_MESSAGE: "draft_message",
  USER_TASK_EXECUTION_TITLE: "user_task_execution_title",
  WORKFLOW_STEP_EXECUTION_STARTED: "workflow_step_execution_started",
  WORKFLOW_STEP_EXECUTION_ENDED: "workflow_step_execution_ended",
  WORKFLOW_EXECUTION_PRODUCED_TEXT: "workflow_execution_produced_text",
  WORKFOW_STEP_EXECUTION_INVALIDATED: "workflow_step_execution_invalidated",
};
