export const socketEvents = {
  CONNECT: "connect",
  START_SESSION: "start_session",
  SESSION_NOT_FOUND: "session_not_found",
  SEARCH_INFO: "search_info",
  MOJO_TOKEN: "mojo_token",
  MOJO_MESSAGE: "mojo_message",
  DISCONNECT: "disconnect",
  ERROR: "error",
  CONNECT_ERROR: "connect_error",
  CONNECT_TIMEOUT: "connect_timeout",
  USER_MESSAGE: "user_message",
  DRAFT_TOKEN: "draft_token",
  DRAFT_MESSAGE: "draft_message",
  USER_TASK_EXECUTION_TITLE: "user_task_execution_title",
};
